//User Input → JS State (array) → UI Update → localStorage
//we have to select the form first
// const form = document.getElementById("transactionForm");
// const textInput = document.getElementById("text");
// const amountInput = document.getElementById("amount");

// const balanceEl = document.getElementById("balance");
// const incomeEl = document.getElementById("income");
// const expenseEl = document.getElementById("expense");

// const list  = document.getElementById("transactionList");
// //here we completed the selection..

// // console.log(form);
// // console.log(textInput);
// // console.log(amountInput);
// // console.log(list);//this is for the text connections

// //we have to store the transaction in the list
// let transactions = [];

// form.addEventListener("submit",addTransaction);

// function addTransaction(e) {
//     e.preventDefault();//this line stops the page refresh...

//     const text = textInput.value.trim();
//     const amount = +amountInput.value.trim();

//     if(text === "" || amount === 0){
//         alert("please enter text and amount");
//         return;
//     }
// //here we create the object
//     const transaction = {
//         id:Date.now(),
//         text:text,
//         amount:amount
//     };

//     transactions.push(transaction);

//     addTransactionToDOM(transaction);
//     updateValues();

//     textInput.value = "";
//     amountInput.value = "";
// }

// function addTransactionToDOM(transaction){
//     const sign = transaction.amount < 0 ? "-" : "+";

//     const li = document.createElement("li");
//     li.classList.add(transaction.amount < 0 ? "minus" : "plus");

//     li.innerHTML = `
//         ${transaction.text}
//         <span>${sign}₹${Math.abs(transaction.amount)}</span>
//     `;

//     list.appendChild(li);
// }

// function updateValues() {
//     const amounts = transactions.map(t => t.amount);

//     const total = amounts.reduce((acc,val) => acc + val,0);
//     const income = amounts.filter(val => val > 0)
//     .reduce((acc,val) => acc+val,0);

//     const expense = amounts.filter(val => val < 0)
//     .reduce((acc,val) => acc+val,0);

//     balanceEl.textContent = `₹${total}`;
//     incomeEl.textContent = `₹${income}`;
//     expenseEl.textContent = `₹${Math.abs(expense)}`;
// }this above code is written by me with the help of ai at every step with learning
//this below code is generated by the claude ai how it looks after give to ai this thing



// Select all elements we need
        const form = document.getElementById("transactionForm");
        const textInput = document.getElementById("text");
        const amountInput = document.getElementById("amount");
        const balanceEl = document.getElementById("balance");
        const incomeEl = document.getElementById("income");
        const expenseEl = document.getElementById("expense");
        const list = document.getElementById("transactionList");

        // Array to store all transactions
        let transactions = [];

        // Load transactions from localStorage when page loads
        function loadTransactions() {
            const savedTransactions = localStorage.getItem("transactions");
            if (savedTransactions) {
                transactions = JSON.parse(savedTransactions);
                transactions.forEach(transaction => addTransactionToDOM(transaction));
                updateValues();
            }
        }

        // Save transactions to localStorage
        function saveToLocalStorage() {
            localStorage.setItem("transactions", JSON.stringify(transactions));
        }

        // Add event listener to form
        form.addEventListener("submit", addTransaction);

        // Function to add new transaction
        function addTransaction(e) {
            e.preventDefault(); // Stop page from refreshing

            const text = textInput.value.trim();
            const amount = +amountInput.value.trim();

            // Validate input
            if (text === "" || amount === 0) {
                alert("Please enter valid text and amount");
                return;
            }

            // Create transaction object
            const transaction = {
                id: Date.now(),
                text: text,
                amount: amount
            };

            // Add to array
            transactions.push(transaction);

            // Add to DOM (display on page)
            addTransactionToDOM(transaction);

            // Update balance, income, expense
            updateValues();

            // Save to localStorage
            saveToLocalStorage();

            // Clear input fields
            textInput.value = "";
            amountInput.value = "";
        }

        // Function to display transaction in the list
        function addTransactionToDOM(transaction) {
            const sign = transaction.amount < 0 ? "-" : "+";

            const li = document.createElement("li");
            li.classList.add(transaction.amount < 0 ? "minus" : "plus");

            li.innerHTML = `
                <span class="transaction-text">${transaction.text}</span>
                <span class="transaction-amount">${sign}₹${Math.abs(transaction.amount)}</span>
                <button class="delete-btn" onclick="removeTransaction(${transaction.id})">Delete</button>
            `;

            list.appendChild(li);
        }

        // Function to remove transaction
        function removeTransaction(id) {
            // Remove from array
            transactions = transactions.filter(transaction => transaction.id !== id);

            // Save to localStorage
            saveToLocalStorage();

            // Clear list and re-render
            list.innerHTML = "";
            transactions.forEach(transaction => addTransactionToDOM(transaction));

            // Update values
            updateValues();
        }

        // Function to update balance, income, and expense
        function updateValues() {
            // Get all amounts from transactions
            const amounts = transactions.map(t => t.amount);

            // Calculate total balance
            const total = amounts.reduce((acc, val) => acc + val, 0);

            // Calculate total income (positive amounts)
            const income = amounts
                .filter(val => val > 0)
                .reduce((acc, val) => acc + val, 0);

            // Calculate total expense (negative amounts)
            const expense = amounts
                .filter(val => val < 0)
                .reduce((acc, val) => acc + val, 0);

            // Update the display
            balanceEl.textContent = `₹${total.toFixed(2)}`;
            incomeEl.textContent = `₹${income.toFixed(2)}`;
            expenseEl.textContent = `₹${Math.abs(expense).toFixed(2)}`;
        }

        // Load transactions when page loads
        loadTransactions();



